config/routes.rb
Rails.application.routes.draw do
	devise_for :users, controllers: {registrations: 'edit_profile',
		confirmations: 'confirmation'}
	
	get 'main_groups/manage'
	patch 'main_groups/edit'
	
	get 'subgroups/manage'
	patch 'subgroups/edit'
	
	get 'subgroups/show_users'
	patch 'subgroups/edit_users'
	
	get 'acolyte/index'
	get 'acolyte/user_offer_self_work'
	patch 'acolyte/save_dispositions'
	get 'acolyte/show_schedule'
	post 'acolyte/generate_schedule'
	get 'acolyte/edit_schedule'
	post 'acolyte/save_schedule'
	get 'acolyte/select_date_ranking'
	get 'acolyte/show_ranking'
	get 'acolyte/write_news'
	post 'acolyte/create_news'
	get 'acolyte/show_news'
	delete 'acolyte/delete_news'
	
	get 'calendar/show'
	get 'calendar/show_event'
	get 'calendar/add_event'
	post 'calendar/create_event'
	get 'calendar/show_event_to_edit'
	patch 'calendar/edit_event'
	delete 'calendar/destroy_event'
	delete 'calendar/destroy_event_series'
	get 'calendar/event_categories'
	patch 'calendar/event_category_edit'
	get 'calendar/show_attendance_list'
	get 'calendar/edit_attendance_list'
	get 'calendar/edit_mandatory_attendance_list'
	post 'calendar/save_attendance_list'
	post 'calendar/save_mandatory_attendance_list'
	get 'calendar/edit_points'
	post 'calendar/save_points'
	
	root 'home#index'

end

app/controllers/calendar_controller.rb
class CalendarController < ApplicationController
	
	def show
		@events = Event.all
	end
	
	def show_event
		@event = Event.find(params[:id])
		if @event.nil?
			flash[:alert] = "Błąd. Spróbuj ponownie."
			return redirect_to request.referrer.nil? ?
					calendar_show_url : request.referrer
		end
		@access = (user_signed_in? and (current_user_is_main_admin or
				current_user_is_organizer(@event) or current_user_is_developer))
		@can_edit_attendance_list = (user_signed_in? and (@access or
			current_user_is_in_organizer_group(@event)))
	end
	
	def add_event
		if user_signed_in? and !current_user.subgroups.find_by(admin: true).nil?
			params[:start_time] = (Time.zone.parse params[:start_time]) + 8.hour
			if params[:end_time].nil?
				params[:end_time] = params[:start_time] + 1.hour
			end
			@event = Event.new(start_time: params[:start_time],
					end_time: params[:end_time])
			@main_groups_to_selected = Array.new
			unless current_user_is_main_admin or current_user_is_developer
				current_user.subgroups.where(admin: true).each do |subgroup|
					if subgroup.main_group.name != "Deweloperzy"
						@main_groups_to_selected << subgroup.main_group
					end
				end
			else
				@main_groups_to_selected = MainGroup.where.not(name: "Deweloperzy")
			end
		else
			flash[:alert] = "Nie masz uprawnień do przeglądania tej podstrony."
			return redirect_to calendar_show_url
		end
	end
	
	def create_event
		if user_signed_in? and !current_user.subgroups.find_by(admin: true).nil?
			if params[:selected_group].nil?
				flash[:alert] = "Nie wybrałeś organizatorów."
				return redirect_to request.referrer
			end
			params[:event][:start_time] = DateTime.civil_from_format :local,
				params[:event]["start_time(1i)"].to_i,
				params[:event]["start_time(2i)"].to_i,
				params[:event]["start_time(3i)"].to_i,
				params[:event]["start_time(4i)"].to_i,
				params[:event]["start_time(5i)"].to_i
			if params[:event]["end_time(4i)"].nil?
				params[:event][:end_time] = (params[:event][:start_time] + 1.day)
					.beginning_of_day()
			else
				params[:event][:end_time] = DateTime.civil_from_format :local,
					params[:event]["end_time(1i)"].to_i,
					params[:event]["end_time(2i)"].to_i,
					params[:event]["end_time(3i)"].to_i,
					params[:event]["end_time(4i)"].to_i,
					params[:event]["end_time(5i)"].to_i
			end
			params[:repeat_end] = DateTime.civil_from_format :local,
				params[:repeat_end]["(1i)"].to_i,
				params[:repeat_end]["(2i)"].to_i,
				params[:repeat_end]["(3i)"].to_i
			# params[:event][:start_time] =
			# 	Time.zone.parse params[:event][:start_time].to_s
			# params[:event][:end_time] =
			# 	Time.zone.parse params[:event][:end_time].to_s
			@founded_category = EventCategory.find(params[:selected_category])
			if params[:overriding_event] != ""
				@overriding_event = Event.find_by(id: params[:overriding_event].to_i)
			end
			if params[:repeat_every_number].to_i == 0
				@repeat = false
			else
				@repeat = true
			end
			@event = nil
			@event_previous = nil
			@date = nil
			begin
				unless @event.nil?
					@event_previous = @event
				end
				@params = params[:event]
				@params[:description] = @params[:description].gsub("\r\n", "<br />")
				@event = @founded_category.events.build({name: @params[:name],
					start_time: @params[:start_time].to_s(:db),
					end_time: @params[:end_time].to_s(:db),
					# start_time: @params[:start_time] - Time.zone.utc_offset.seconds,
					# end_time: @params[:end_time] - Time.zone.utc_offset.seconds,
					description: @params[:description], color: @params[:color]})
				# @event = @founded_category.events.build(event_params)
				@event.save!
				if @date.nil?
					@date = @event.start_time.to_date
				end
				unless @event_previous.nil?
					@event_previous.next_in_series_event = @event
				end
				MainGroup.all.each do |group|
					if params[group.id.to_s]
						@property = nil
						if params[group.id.to_s][:mandatory_presence].to_i > 0
							if !params[:selected_group].include?(group.id.to_s)
								@property = group.event_properties.build({organizer: false,
									mandatory_presence: params[group.id.to_s][:number_mandatory]})
							else
								@property = group.event_properties.build({organizer: true,
									mandatory_presence: params[group.id.to_s][:number_mandatory]})
							end
							@property.save!
							@event.event_properties << @property
							@event.save!
						elsif params[:selected_group].include?(group.id.to_s)
							@property = group.event_properties.build({organizer: true,
								mandatory_presence: 0})
							@property.save!
							@event.event_properties << @property
						end
					end
				end
				if !@overriding_event.nil?
					@overriding_event.related_events << @event
					@overriding_event.save!
					@overriding_event = @overriding_event.next_in_series_event
				end
				@event.save!
				case params[:repeat_every_type].to_i
				when 0
					params[:event][:start_time] +=
						params[:repeat_every_number].to_i.days
					params[:event][:end_time] +=
						params[:repeat_every_number].to_i.days
				when 1
					params[:event][:start_time] +=
						params[:repeat_every_number].to_i.weeks
					params[:event][:end_time] +=
						params[:repeat_every_number].to_i.weeks
				when 2
					params[:event][:start_time] +=
						params[:repeat_every_number].to_i.months
					params[:event][:end_time] +=
						params[:repeat_every_number].to_i.months
				when 3
					params[:event][:start_time] +=
						params[:repeat_every_number].to_i.years
					params[:event][:end_time] +=
						params[:repeat_every_number].to_i.years
				end
				if params[:event][:start_time] > params[:repeat_end] + 1.day
					@repeat = false
				end
			end while @repeat
			flash[:notice] = "Utworzono nowe wydarzenie."
      return redirect_to calendar_show_url(start_date: @date)
		else
			flash[:alert] = "Nie masz uprawnień do przeglądania tej podstrony."
			return redirect_to calendar_show_url
		end
	end
	
	def show_event_to_edit
		@event = Event.find(params[:id])
		@date = @event.start_time.to_date
		unless user_signed_in? and (current_user_is_main_admin or
				current_user_is_organizer(@event) or current_user_is_developer)
			flash[:alert] = "Nie masz uprawnień do przeglądania tej podstrony."
			return calendar_show_url(start_date: @date)
		end
		@organizers = Array.new
		@main_groups_to_selected = Array.new
		@event.event_properties.where(organizer: true).each do
				|organizer_property|
			@organizers << organizer_property.main_group.id
		end
		unless current_user_is_main_admin or current_user_is_developer
			current_user.subgroups.where(admin: true).each do |subgroup|
				if subgroup.main_group.name != "Deweloperzy"
					@main_groups_to_selected << subgroup.main_group
				end
			end
		else
			@main_groups_to_selected = MainGroup.where.not(name: "Deweloperzy")
		end
		@event.description = @event.description.gsub("<br />", "\r\n")
	end
	
	def edit_event
		@event = Event.find(params[:event][:id])
		@date = @event.start_time.to_date
		if current_user_is_organizer(@event) or current_user_is_developer
			if params[:selected_group].nil?
				flash[:alert] = "Nie wybrałeś organizatorów."
				return redirect_to request.referrer
			end
			params[:event][:start_time] = DateTime.civil_from_format :local,
				params[:event]["start_time(1i)"].to_i,
				params[:event]["start_time(2i)"].to_i,
				params[:event]["start_time(3i)"].to_i,
				params[:event]["start_time(4i)"].to_i,
				params[:event]["start_time(5i)"].to_i
			if params[:event]["end_time(4i)"].nil?
				params[:event][:end_time] = params[:event][:start_time].end_of_day
			else
				params[:event][:end_time] = DateTime.civil_from_format :local,
					params[:event]["end_time(1i)"].to_i,
					params[:event]["end_time(2i)"].to_i,
					params[:event]["end_time(3i)"].to_i,
					params[:event]["end_time(4i)"].to_i,
					params[:event]["end_time(5i)"].to_i
			end
			params[:event][:start_time] =
				Time.zone.parse params[:event][:start_time].to_s
			params[:event][:end_time] = Time.zone.parse params[:event][:end_time].to_s
			@founded_category = EventCategory.find(params[:selected_category])
			params[:event][:description] =
					params[:event][:description].gsub("\r\n", "<br />")
			@event.update_attributes(event_params)
			if @event.event_category != @founded_category
				unless @event.event_category.nil?
					@event.event_category.events.delete(@event)
				end
				@founded_category.events << @event
			end
			MainGroup.all.each do |group|
				if params[group.id.to_s]
					@property = @event.event_properties.find_by(main_group_id: group.id)
					if params[group.id.to_s][:mandatory_presence].to_i > 0
						if !params[:selected_group].include?(group.id.to_s)
							if !@property.nil?
								@property.update_attributes({organizer: false,
									mandatory_presence: params[group.id.to_s][:number_mandatory]})
							else
								@property = group.event_properties.build({organizer: false,
									mandatory_presence: params[group.id.to_s][:number_mandatory]})
								@property.save!
								@event.event_properties << @property
							end
						else
							if !@property.nil?
								@property.update_attributes({organizer: true,
									mandatory_presence: params[group.id.to_s][:number_mandatory]})
							else
								@property = group.event_properties.build({organizer: true,
									mandatory_presence: params[group.id.to_s][:number_mandatory]})
								@property.save!
								@event.event_properties << @property
							end
						end
						@event.save!
					elsif params[:selected_group].include?(group.id.to_s)
						if !@property.nil?
							@property.update_attributes(
								{organizer: true, mandatory_presence: 0})
						else
							@property = group.event_properties.build({organizer: true,
								mandatory_presence: 0})
							@property.save!
							@event.event_properties << @property
						end
						@event.save!
					elsif !params[:selected_group].include?(group.id.to_s) and
							!@event.main_groups.find_by(id: group.id).nil?

app/views/calendar/add_event.html.erb
<%= form_for @event, as: @event, url: calendar_create_event_url,
		html: { method: :post } do |f| %>
	<div id="main" class="panel panel-default">
		<div id="main" class="panel-heading">
			<h4>Tworzenie wydarzenia</h4>
		</div>
		<div id="main" class="panel-body" style="overflow-y: auto">
			<div class="form-group">
				<%= f.label :name, "Nazwa" %>
        <%= f.text_field :name, autofocus: true, class: "form-control" %>
			</div>
			<div class="form-group">
				<%= f.label :start_time, "Początek" %>
				<div class="form-inline">
        	<%= f.datetime_select :start_time,
        		{
        			prompt: true,
              end_year: Date.today.year - 110, start_year: Date.today.year + 5,
              date_separator: '', time_separator: '', minute_step: 5,
              datetime_separator: ' o godzinie: '
            },
        		{ class: "form-control" }
        	%>
        </div>
			</div>
			<div class="form-group">
				<%= f.label :end_time, "Koniec" %>
				<div class="form-inline">
        	<%= f.datetime_select :end_time,
        		{
        			prompt: true,
              end_year: Date.today.year - 110, start_year: Date.today.year + 5,
              date_separator: '', time_separator: '', minute_step: 5,
              datetime_separator: ' o godzinie: '
            },
        		{ class: "form-control" }
        	%>
        </div>
			</div>
			<div class="form-group">
				<%= f.label :description, "Opis" %>
        <%= f.text_area :description, class: "form-control" %>
			</div>
			<div class="form-group">
				<%= f.label :color, "Kolor" %>
        <%= f.select :color, [["Biały", "default"], ["Niebieski", "primary"],
        	["Zielony", "success"], ["Błękitny", "info"],
        	["Pomarańczowy", "warning"], ["Czerwony", "danger"],
        	["Fioletowy", "purple"], ["Różowy", "pink"], ["Czarny", "black"],
        	["Żółty", "yellow"]].sort, {
        		selected: "warning"
        	},
        	{ class: "form-control" }
        %>
			</div>
			<div class="form-group">
				<%= f.label :main_groups, "Organizatorzy" %>
				<i>(wybierając wiele trzymaj wciśnięty <b>CTRL</b>)</i>
				<%= select_tag :selected_group,
				options_from_collection_for_select(
					@main_groups_to_selected.sort_by { |g| g.name }, "id", "name"),
				{ class: "form-control", size: 5, :multiple => true } %>
			</div>
			<div class="form-horizontal">
				<%= label_tag :mandatory_presence, "Obowiązkowo obecni" %>
				<% MainGroup.all.each do |group| %>
					<% if group.name != "Deweloperzy" %>
						<div class="form-group">
							<div class="col-xs-4 col-sm-5 control-label"
									style="word-wrap: break-word; text-align: right">
								<%= group.name %>
							</div>
							<div class="col-xs-5 col-sm-2">
								<div class="text-center">
									<div class="checkbox">
										<%= check_box group.id, :mandatory_presence,
											disabled: group.users.empty? %>
										<%= "Liczba osób: " %>
									</div>
								</div>
							</div>
							<div class="col-xs-3 col-sm-2 col-lg-1">
								<%= number_field_tag group.id.to_s + "[number_mandatory]", "",
									{ class: "form-control", disabled: true, min: 1,
									max: group.users.size, step: 1 } %>
							</div>
						</div>
					<% end %>
				<% end %>
			</div>
			<div class="form-group">
				<%= label_tag :selected_category, "Kategoria" %>
				<%= select_tag :selected_category,
				options_from_collection_for_select(
					EventCategory.all.collect.sort_by { |g| g.name }, "id", "name"),
				{ class: "form-control", size: 0 } %>
			</div>
			<div class="form-group">
				<%= label_tag :overriding_event, "Powiąż z" %>
				<%= select_tag :overriding_event,
				options_from_collection_for_select(
					Event.all.collect.sort_by { |g| g.start_time },
						:id, :start_time_and_name),
				{ class: "form-control", size: 0, include_blank: true } %>
			</div>
			<div class="form-group">
				<%= label_tag :repeat_every, "Powtarzaj co:" %>
				<div class="form-inline">
					<%= number_field_tag :repeat_every_number, 0,
						{ class: "form-control", disabled: false, min: 0,
						max: 99, step: 1, style: "width: 100px" } %>
					<%= select_tag :repeat_every_type,
						options_for_select([["dzień", "0"],
							["tydzień", "1"], ["miesiąc", "2"], ["rok", "3"]], "1"),
						{ class: "form-control", size: 0, include_blank: false } %>
				</div>
			</div>
			<div class="form-group">
				<%= label_tag :repeat_every, "Powtarzaj do:" %>
				<div class="form-inline">
        	<%= date_select :repeat_end, "",
      			{ prompt: false,
      				end_year: Date.today.year, start_year: Date.today.year + 10
      			},
            { class: "form-control" }
        	%>
        </div>
			</div>
		</div>
		<div id="main" class="panel-footer">
			<div class="text-center">
				<%= f.submit "Dodaj wydarzenie" , class: "btn btn-primary" %>
			</div>
		</div>
	</div>
<% end %>

app/views/calendar/show.html.erb
<div id="main" class="panel panel-default">
<%= month_calendar events: @events do |date, events| %>
	<div class="pull-left">
		<%= date.day %>
	</div>
	<% if user_signed_in? and !current_user.subgroups.find_by(admin: true).nil? %>
		<%#= form_for Event.new, url: calendar_add_event_url,
				html: { class: "form-inline", method: :get } do |f| %>
			<%#= f.hidden_field :start_time, value: date %>
			<%#= button_tag class: "btn btn-link btn-xs pull-right" do %>
				<%#= "<span class='glyphicon glyphicon-plus' aria-hidden='true'>
				</span>".html_safe %>
		<%= link_to calendar_add_event_url(start_time: date),
				class: "btn btn-link btn-xs pull-right" do %>
			<%= "<span class='glyphicon glyphicon-plus' aria-hidden='true'>
			</span>".html_safe %>
		<% end %>
		<%# end %>
	<% end %><br />
	<% events.collect.sort_by{ |e| e.start_time }.each do |event| %>
		<div style="font-size: 71.43%; line-height: 215%;">
			<div class="row" style="padding: 1px 0px; margin: 0px -9px">
				<div class="col-lg-4">
					<%= event.start_time.to_s(:time) %>
				</div>
				<div class="col-lg-8">
					<%= link_to event.name, calendar_show_event_url(id: event.id),
						{ method: :get,
							class: ("btn btn-" + event.color + " btn-sm btn-block"),
							style: "white-space: normal; word-wrap: break-word;
									hyphens: auto;",
							lang: "pl"
						} %>
				</div>
			</div>
		</div>
	<% end %>
<% end %>
</div>

app/views/calendar/show_event.html.erb
<div id="main" class="panel panel-default">
	<div id="main" class="panel-heading">
		<h1><%= @event.name %></h1>
	</div>
	<div id="main" class="panel-body" style="font-size: 140%">
		<div class="row">
			<div class="col-sm-2 col-sm-offset-3 col-md-1 col-md-offset-4"
					style="font-weight: bold; font-size: 90%; line-height: 160%">
				<p>Data:</p>
			</div>
			<div class="col-sm-6">
				<p>
					<%= l @event.start_time, format: "%A" %>,
					<%= l @event.start_time.to_date %>
				</p>
			</div>
		</div>
		<div class="row">
			<div class="col-sm-2 col-sm-offset-3 col-md-1 col-md-offset-4"
					style="font-weight: bold; font-size: 90%; line-height: 160%">
				<p>Godzina:</p>
			</div>
			<div class="col-sm-6">
				<p><%= l @event.start_time, format: "%H:%M" %></p>
			</div>
		</div>
		<div class="row">
			<div class="col-sm-2 col-sm-offset-3 col-md-1 col-md-offset-4"
					style="font-weight: bold; font-size: 90%; line-height: 160%">
				<p>Opis:</p>
			</div>
			<div class="col-sm-6">
				<p><%= @event.description.html_safe %></p>
			</div>
		</div>
	</div>
	<% if @access %>
		<div id="main" class="panel-footer">
			<div class="form-group" style="text-align: center">
				<%= link_to "Edytuj wydarzenie", calendar_show_event_to_edit_url(id: @event.id),
				  	{ method: :get, class: "btn btn-primary" } %>
				<%= link_to "Lista obecności",
						calendar_show_attendance_list_url(id: @event.id),
				  	{ method: :get, class: "btn btn-primary" } %>
			</div>
			<div class="form-group">
				<%= button_to "Usuń", calendar_destroy_event_url(id: @event.id),
					  data: { confirm: "Czy na pewno chcesz usunąć to wydarzenie" },
					  method: :delete, class: "btn btn-danger btn-xs" %>
			</div>
			<div>
			  <%= button_to "Usuń to i następne w serii",
				  	calendar_destroy_event_series_url(id: @event.id),
					  data: { confirm: "Czy na pewno chcesz usunąć to i następne " +
					  		"wydarzenia w serii" },
					  method: :delete, class: "btn btn-danger btn-xs" %>
			  <i>Operacji nie da się cofnąć!</i>
			</div>
		</div>
	<% elsif @can_edit_attendance_list %>
		<div id="main" class="panel-footer">
			<div class="form-group" style="text-align: center">
				<%= link_to "Lista obecności",
						calendar_show_attendance_list_url(id: @event.id),
				  	{ method: :get, class: "btn btn-primary" } %>
			</div>
		</div>
	<% end %>
</div>

app/views/calendar/show_event_to_edit.html.erb
<div id="main" class="panel panel-default">
	<div id="main" class="panel-heading">
		<h4>Edycja wydarzenia</h4>
	</div>
	<%= form_for @event, as: @event, url: calendar_edit_event_url,
			html: { method: :patch } do |f| %>
		<div id="main" class="panel-body" style="overflow-y: auto">
			<div class="form-group">
				<%= f.hidden_field :id, value: @event.id %>
			</div>
			<div class="form-group">
				<%= f.label :name, "Nazwa" %>
        <%= f.text_field :name, autofocus: true, class: "form-control" %>
			</div>
			<div class="form-group">
				<%= f.label :start_time, "Początek" %>
				<div class="form-inline">
        	<%= f.datetime_select :start_time,
        		{
        			prompt: true,
              end_year: Date.today.year - 110, start_year: Date.today.year + 5,
              date_separator: '', time_separator: '', minute_step: 5,
              datetime_separator: ' o godzinie: '
            },
        		{ class: "form-control" }
        	%>
        </div>
			</div>
			<div class="form-group">
				<%= f.label :end_time, "Koniec" %>
				<div class="form-inline">
        	<%= f.datetime_select :end_time,
        		{
        			prompt: true,
              end_year: Date.today.year - 110, start_year: Date.today.year + 5,
              date_separator: '', time_separator: '', minute_step: 5,
              datetime_separator: ' o godzinie: '
            },
        		{ class: "form-control" }
        	%>
        </div>
			</div>
			<div class="form-group">
				<%= f.label :description, "Opis" %>
        <%= f.text_area :description, class: "form-control" %>
			</div>
			<div class="form-group">
				<%= f.label :color, "Kolor" %>
        <%= f.select :color, [["Biały", "default"], ["Niebieski", "primary"],
        	["Zielony", "success"], ["Błękitny", "info"],
        	["Pomarańczowy", "warning"], ["Czerwony", "danger"],
        	["Fioletowy", "purple"], ["Różowy", "pink"], ["Czarny", "black"],
        	["Żółty", "yellow"]].sort, {},
        	{ class: "form-control" }
        %>
			</div>
			<div class="form-group">
				<%= f.label :main_groups, "Organizatorzy" %>
				<i>(wybierając wiele trzymaj wciśnięty <b>CTRL</b>)</i>
				<%= select_tag :selected_group,
				options_from_collection_for_select(
					@main_groups_to_selected.sort_by { |g| g.name }, "id", "name",
					@organizers),
				{ class: "form-control", size: 5, :multiple => true } %>
			</div>
			<div class="form-horizontal">
				<% MainGroup.all.each do |group| %>
					<% if group.name != "Deweloperzy" %>
						<div class="form-group">
							<div class="col-xs-4 col-sm-5 control-label"
									style="word-wrap: break-word; text-align: right">
								<%= group.name %>
							</div>
							<div class="col-xs-5 col-sm-2">
								<div class="text-center">
									<div class="checkbox">
										<%= check_box group.id, :mandatory_presence,
											disabled: group.users.empty?,
											checked:
											(
												if @event.event_properties
														.find_by(main_group_id: group.id)
													@event.event_properties
														.find_by(main_group_id: group.id)
														.mandatory_presence > 0
												else
													false
												end
											)
										%>
										<%= "Liczba osób: " %>
									</div>
								</div>
							</div>
							<div class="col-xs-3 col-sm-2 col-lg-1">
								<%= number_field_tag group.id.to_s + "[number_mandatory]",
									(
										if @event.event_properties
												.find_by(main_group_id: group.id) and
												@event.event_properties
													.find_by(main_group_id: group.id)
													.mandatory_presence > 0
											@event.event_properties.find_by(main_group_id: group.id)
												.mandatory_presence
										else
											""
										end
									),
									{ class: "form-control", disabled: false, min: 1,
									disabled:
									(
										if @event.event_properties.find_by(main_group_id: group.id)
											@event.event_properties.find_by(main_group_id: group.id)
												.mandatory_presence == 0
										else
											true
										end
									),
									max: group.users.size, step: 1 } %>
							</div>
						</div>
					<% end %>
				<% end %>
			</div>
			<div class="form-group">
				<%= label_tag :selected_category, "Kategoria" %>
				<%= select_tag :selected_category,
				options_from_collection_for_select(
					EventCategory.all.collect.sort_by { |g| g.name }, "id", "name",
					@event.event_category.nil? ? 0 : @event.event_category.id),
				{ class: "form-control", size: 0 } %>
			</div>
			<div class="form-group">
				<%= label_tag :overriding_event, "Powiązane z" %>
				<%= select_tag :overriding_event,
				options_from_collection_for_select(
					Event.all.collect.sort_by { |g| g.start_time },
						:id, :start_time_and_name,
						@event.overriding_event.nil? ? 0 : @event.overriding_event.id),
				{ class: "form-control", size: 0, include_blank: true } %>
			</div>
		</div>
		<div id="main" class="panel-footer">
			<div class="text-center">
				<div class="form-group">
					<%= f.submit "Edytuj wydarzenie" , class: "btn btn-primary" %>
				</div>
			</div>
			<!--<form>-->
			<!--	<div class="pull-left">-->
			<!--		<%#= button_to "Usuń", calendar_destroy_event_url(id: @event.id),-->
			<!--		  data: { confirm: "Czy na pewno chcesz usunąć to wydarzenie" },-->
			<!--		  method: :delete, class: "btn btn-danger btn-xs" %>-->
			<!--  	<i>Operacji nie da się cofnąć!</i>-->
			<!--	</div>-->
			<!--</form>-->
		</div>
	<% end %>
</div>