config/routes.rb
Rails.application.routes.draw do
	devise_for :users, controllers: {registrations: 'edit_profile',
		confirmations: 'confirmation'}
	
	get 'main_groups/manage'
	patch 'main_groups/edit'
	
	get 'subgroups/manage'
	patch 'subgroups/edit'
	
	get 'subgroups/show_users'
	patch 'subgroups/edit_users'
	
	get 'acolyte/index'
	get 'acolyte/user_offer_self_work'
	patch 'acolyte/save_dispositions'
	get 'acolyte/show_schedule'
	post 'acolyte/generate_schedule'
	get 'acolyte/edit_schedule'
	post 'acolyte/save_schedule'
	get 'acolyte/select_date_ranking'
	get 'acolyte/show_ranking'
	get 'acolyte/write_news'
	post 'acolyte/create_news'
	get 'acolyte/show_news'
	delete 'acolyte/delete_news'
	
	get 'calendar/show'
	get 'calendar/show_event'
	get 'calendar/add_event'
	post 'calendar/create_event'
	get 'calendar/show_event_to_edit'
	patch 'calendar/edit_event'
	delete 'calendar/destroy_event'
	delete 'calendar/destroy_event_series'
	get 'calendar/event_categories'
	patch 'calendar/event_category_edit'
	get 'calendar/show_attendance_list'
	get 'calendar/edit_attendance_list'
	get 'calendar/edit_mandatory_attendance_list'
	post 'calendar/save_attendance_list'
	post 'calendar/save_mandatory_attendance_list'
	get 'calendar/edit_points'
	post 'calendar/save_points'
	
	root 'home#index'

end

app/controllers/acolyte_controller.rb
class AcolyteController < ApplicationController
	def index
		@access_admin = access_admin
		@access_moderator = access_moderator
		@current_group = MainGroup.find_by(name: "Ministranci")
		@page = params[:page].nil? ? 1 : params[:page].to_i
		@per_page = params[:per_page].nil? ? 5 : params[:per_page].to_i
		@pages_to_show = Array.new
		if @current_group.news.size > 0
			@news = @current_group.news.reverse.to_a
			@news_to_show = Array.new
			@pages = (@news.size / @per_page).to_i +
					(@news.size % @per_page > 0 ? 1 : 0)
			if @page > @pages
				@page = @pages
			elsif @page < 1
				@page = 1
			end
			((@page - 1) * @per_page).upto(@page * @per_page - 1) do |i|
				if @news.size > i
					@news_to_show << @news[i]
				end
			end
			@counter = 0
			((@page - 3)..(@page + 3)).each do |i|
				if i > 0 and i < @pages + 1
					@pages_to_show << i
					@counter += 1
				end
			end
			if @counter < @pages and @counter < 7
				(1..(7 - @counter)).each do |i|
					if @page - 3 < 1
						@pages_to_show << (@page + 3 + i)
					elsif @page + 3 > @pages
						@pages_to_show << (@page - 3 - i)
					end
				end
			end
			@pages_to_show.sort!
		else
			@page = 1
			@pages = 1
			@pages_to_show << 1
		end
	end
	
	def user_offer_self_work
		@categories = Array.new
		@current_group = MainGroup.find_by(name: "Ministranci")
		unless current_user_is_acolyte
			flash[:alert] = "Nie masz uprawnień do przeglądania tej podstrony."
			return redirect_to acolyte_index_url
		else
			@current_group.event_properties.where("mandatory_presence > ?", 0)
					.each do |property|
				if !@categories.include? property.event.event_category
					@categories << property.event.event_category
				end
			end
		end
	end
	
	def save_dispositions
		@current_group = MainGroup.find_by(name: "Ministranci")
		unless current_user_is_acolyte
			flash[:alert] = "Nie masz uprawnień do przeglądania tej podstrony."
			return redirect_to acolyte_index_url
		else
			current_user.dispositions.clear()
			EventCategory.all.each do |category|
				unless params[category.id.to_s].nil?
					params[category.id.to_s][:weekday].each do |weekday|
						params[category.id.to_s][:hour].each do |hour|
							if params[category.id.to_s][weekday][hour] == "1"
								@disposition = current_user.dispositions
									.build({weekday: weekday, hour: hour.to_s})
								@disposition.save!
								category.dispositions << @disposition
							end
						end
					end
				end
			end
			return redirect_to acolyte_user_offer_self_work_url
		end
	end
	
	def show_schedule
		@categories = Array.new
		@current_group = MainGroup.find_by(name: "Ministranci")
		unless current_user_is_acolyte
			flash[:alert] = "Nie masz uprawnień do przeglądania tej podstrony."
			return redirect_to acolyte_index_url
		else
			@current_group.event_properties.where("mandatory_presence > ?", 0)
					.each do |property|
				if !@categories.include? property.event.event_category
					@categories << property.event.event_category
				end
			end
		end
	end
	
	def generate_schedule
		@current_group = MainGroup.find_by(name: "Ministranci")
		@categories = Array.new
		unless access_admin
			flash[:alert] = "Nie masz uprawnień do przeglądania tej podstrony."
			return redirect_to acolyte_show_schedule_url
		else
			@current_group.work_plans.destroy_all
			@current_group.event_properties.where("mandatory_presence > ?", 0)
					.each do |property|
				if !@categories.include? property.event.event_category
					@categories << property.event.event_category
				end
			end
			@categories.each do |category|
				if category.schedule_type == "weekly"
					@days = Array.new
					@hours_in_days = Array.new
					@hours = Array.new
					category.events.each do |event|
						unless event.mandatory_attendance_list.nil?
							event.mandatory_attendance_list.destroy!
							event.mandatory_attendance_list = nil
							event.save!
							unless event.mandatory_attendance_list.nil?
								byebug
							end
						end
						@event_ok = false
						event.event_properties.where("mandatory_presence > ?", 0)
								.each do |property|
							if @event_ok = property.main_group.id == @current_group.id
								break
							end
						end
						if @event_ok
							if !@days.include? event.start_time.wday
								@days << event.start_time.wday
								@hours_in_days[event.start_time.wday] = Array.new
							end
							if !@hours.include? event.start_time.to_s(:time)
								@hours << event.start_time.to_s(:time)
							end
						end
					end
					@days.sort!
					@hours.sort!.each do |hour|
						@days.each do |weekday|
							category.events.each do |event|
								@event_ok = false
								event.event_properties.where("mandatory_presence > ?", 0)
										.each do |property|
									if @event_ok = property.main_group.id == @current_group.id
										break
									end
								end
								if @event_ok
									if event.start_time.wday == weekday and
											event.start_time.to_s(:time) == hour
										@current_group.users.each do |user|
											if !user.dispositions
													.find_by(weekday: weekday, hour: hour).nil?
												@work_plan = user.work_plans
													.find_by(main_group_id: @current_group.id)
												if @work_plan.nil?
													@work_plan = user.work_plans.build()
													@work_plan.save!
													@current_group.work_plans << @work_plan
												end
												@task = @work_plan.tasks.build()
												@task.save!
												event.tasks << @task
												@man_att_list = event.mandatory_attendance_list
												if @man_att_list.nil?
													@man_att_list = 
															event.build_mandatory_attendance_list
													@man_att_list.save!
												end
												@man_att_list.users << user
											end
										end
									end	
								end
							end
						end
					end
				end
			end
			return redirect_to acolyte_show_schedule_url
		end
	end
	
	def edit_schedule
		@categories = Array.new
		@current_group = MainGroup.find_by(name: "Ministranci")
		unless access_admin
			flash[:alert] = "Nie masz uprawnień do przeglądania tej podstrony."
			return redirect_to acolyte_index_url
		else
			@current_group.event_properties.where("mandatory_presence > ?", 0)
					.each do |property|
				if !@categories.include? property.event.event_category
					@categories << property.event.event_category
				end
			end
		end
	end
	
	def save_schedule
		@current_group = MainGroup.find_by(name: "Ministranci")
		unless access_admin
			flash[:alert] = "Nie masz uprawnień do przeglądania tej podstrony."
			return redirect_to acolyte_index_url
		else
			@current_group.work_plans.destroy_all
			@current_group.save!
			EventCategory.all.each do |category|
				if category.schedule_type == "weekly"
					category.events.each do |event|
						unless event.mandatory_attendance_list.nil?
							event.mandatory_attendance_list.destroy!
							event.mandatory_attendance_list = nil
							event.save!
							unless event.mandatory_attendance_list.nil?
								byebug
							end
						end
					end
					params[category.id.to_s][:weekday].each do |weekday|
						params[category.id.to_s][:hour].each do |hour|
							@events = Array.new
							category.events.each do |event|
								if event.start_time.wday.to_s == weekday and
										event.start_time.to_s(:time) == hour
									@events << event
								end
							end
							if !params[category.id.to_s].nil? and
									!params[category.id.to_s][weekday.to_s].nil? and
									!params[category.id.to_s][weekday.to_s][hour.to_s].nil?
								params[category.id.to_s][weekday.to_s][hour.to_s]
										.each do |user_id|
									if user_id != ""
										@user = User.find_by(id: user_id.to_i)
										if !@user.nil?
											@work_plan = @user.work_plans
												.find_by(main_group_id: @current_group.id)
											@work_plan_nil = false
											if @work_plan.nil?
												@work_plan = @user.work_plans.build()
												@work_plan.save!
												@current_group.work_plans << @work_plan
												@work_plan.save!
												@current_group.save!
												@work_plan_nil = true
											end
											# @task = @work_plan.tasks.build()
											# @task.save!
											@none_event = true
											@events.each do |event|
												if @work_plan.tasks.find_by(event_id: event.id).nil?
													@task = @work_plan.tasks.build()
													@task.save!
													event.tasks << @task
													@task.save!
													event.save!
													@none_event = false
													@man_att_list = event.mandatory_attendance_list
													if @man_att_list.nil?
														@man_att_list =
																event.build_mandatory_attendance_list
														@man_att_list.save!
														event.save!
													end
													if @man_att_list.users.find_by(id: @user.id).nil?
														@man_att_list.users << @user
														@man_att_list.save!
														@user.save!
														event.save!
													end
												end
											end
											if @none_event
												# @work_plan.tasks.destroy(@task)
												if @work_plan_nil
													@user.work_plans.destroy(@work_plan)
												end
											end
										end
									end
								end
							end
						end
					end
				end
			end
			return redirect_to acolyte_show_schedule_url
		end
	end
	
	def select_date_ranking
	end
	
	def show_ranking
		@current_group = MainGroup.find_by(name: "Ministranci")
		@start = Date.new params[:start]["date(1i)"].to_i,
				params[:start]["date(2i)"].to_i,
				params[:start]["date(3i)"].to_i
		@end = Date.new params[:end]["date(1i)"].to_i,
				params[:end]["date(2i)"].to_i,
				params[:end]["date(3i)"].to_i
		@events = Array.new
		Event.all.each do |event|
			if event.start_time >= @start.beginning_of_day and
					event.start_time <= @end.end_of_day
				@events << event
			end
		end
	end
	
	def write_news
		unless access_moderator or access_admin
			flash[:alert] = "Nie masz uprawnień do przeglądania tej podstrony."

app/views/acolyte/edit_schedule.html.erb
<div id="main" class="panel panel-default">
	<div id="main" class="panel-heading">
		<h4>Grafik</h4>
	</div>
	<div id="select_model" style="display: none;">
		<%= select_tag @name, options_from_collection_for_select(
			@current_group.users.sort_by{ |u| u.last_name }, "id", "full_name"),
			{ class: "form-control", style: "min-width: 120px", size: 0,
				include_blank: true }
		%>
	</div>
	<%= form_tag acolyte_save_schedule_url, method: :post do %>
		<div id="main" class="panel-body" style="overflow-y: auto">
			<% @categories.each do |category| %>
				<% if category.schedule_type == "weekly" %>
					<% @days = Array.new %>
					<% @hours_in_days = Array.new %>
					<% @hours = Array.new %>
					<div class="table-responsive">
						<table class="table table-bordered">
							<% @title_show = false %>
							<% category.events.each do |event| %>
								<% @event_ok = false %>
								<% @properties =
										event.event_properties.where("mandatory_presence > ?", 0) %>
								<% if @properties.length > 0 and not @title_show %>
									<caption><%= category.name %></caption>
									<% @title_show = true %>
								<% end %>
								<% @properties.each do |property| %>
									<% if @event_ok = property.main_group.id ==
											@current_group.id %>
										<% break %>
									<% end %>
								<% end %>
								<% if @event_ok %>
									<% if !@days.include? event.start_time.wday %>
										<% @days << event.start_time.wday %>
										<% @hours_in_days[event.start_time.wday] = Array.new %>
										<%= hidden_field_tag category.id.to_s +
											"[weekday][]", event.start_time.wday %>
									<% end %>
									<% if !@hours.include? event.start_time.to_s(:time) %>
										<% @hours << event.start_time.to_s(:time) %>
										<%= hidden_field_tag category.id.to_s +
											"[hour][]", event.start_time.to_s(:time) %>
									<% end %>
								<% end %>
							<% end %>
							<thead>
								<tr>
									<th><div class="text-center">#</div></th>
									<% @days.sort!.each do |weekday| %>
										<% if weekday != 0 %>
											<th>
												<div class="text-center">
													<%= I18n.t(:"date.abbr_day_names")[weekday] %>
												</div>
											</th>
										<% end %>
									<% end %>
									<% @sunday = false %>
									<% @days.each do |weekday| %>
										<% if weekday == 0 %>
											<th>
												<div class="text-center">
													<%= I18n.t(:"date.abbr_day_names")[weekday] %>
												</div>
											</th>
											<% @sunday = true %>
											<% @days.delete(weekday) %>
										<% end %>
									<% end %>
									<% if @sunday == true %>
										<% @days << 0 %>
									<% end %>
								</tr>
							</thead>
							<tbody>
								<% @hours.sort!.each do |hour| %>
									<tr>
										<th scope="row">
											<div class="text-center"><%= hour %></div>
										</th>
										<% @days.each do |weekday| %>
											<td>
												<div id="cell_<%= category.id.to_s + "_" +
													weekday.to_s + "_" + hour.to_s %>">
													<% category.events.each do |event| %>
														<% @event_ok = false %>
														<% event.event_properties
																.where("mandatory_presence > ?", 0)
																.each do |property| %>
															<% if @event_ok =
																	property.main_group.id == @current_group.id %>
																<% break %>
															<% end %>
														<% end %>
														<% if @event_ok %>
															<% if event.start_time.wday == weekday and
																	event.start_time.to_s(:time) == hour %>
																<% if !@hours_in_days.at(weekday)
																		.include?(hour) %>
																	<% @hours_in_days.at(weekday) << hour %>
																	<div class="text-right form-group">
																		<div id="add_<%= category.id.to_s + "_" +
																				weekday.to_s + "_" + hour.to_s %>"
																				class="btn btn-default btn-xs">
																			<span class="glyphicon glyphicon-plus"
																				aria-hidden="true">
																			</span>
																		</div>
																	</div>
																	<% @current_group.users.each do |user| %>
																		<% @work_plan = user.work_plans.find_by(
																			main_group_id: @current_group.id) %>
																		<% if !@work_plan.nil? %>
																			<% @work_plan.tasks.where(event_id:
																					Event.where(event_category_id:
																						category.id)).each do |task| %>
																				<% if task.event.start_time
																						.to_s(:time) == hour and
																						task.event.start_time.wday ==
																						weekday %>
																					<div class="form-group">
																						<% @name = category.id.to_s +
																							"[" + weekday.to_s + "]" +
																							"[" + hour.to_s + "][]" %>
																						<%= select_tag @name,
																							options_from_collection_for_select(
																								@current_group.users
																									.sort_by{ |u| u.last_name },
																								"id", "full_name", user.id),
																							{ class: "form-control",
																								style: "min-width: 120px",
																								size: 0, include_blank: true}
																						%>
																					</div>
																					<% break %>
																				<% end %>
																			<% end %>
																		<% end %>
																	<% end %>
																<% end %>
															<% end %>
														<% end %>
													<% end %>
												</div>
											</td>
										<% end %>
									</tr>
								<% end %>
							</tbody>
						</table>
					</div>
				<% end %>
			<% end %>
		</div>
		<div id="main" class="panel-footer">
			<div class="text-center">
				<%= button_tag "Zapisz", class: "btn btn-primary" %>
			</div>
		</div>
	<% end %>
</div>

app/views/acolyte/index.html.erb
<div id="main" class="panel panel-default">
	<div id="main" class="panel-heading">
		<% if @access_moderator or @access_admin %>
			<div class="pull-right">
				<%= link_to "Nowy wpis", acolyte_write_news_url,
		  			method: :get, class: "btn btn-success" %>
		  </div>
	  <% end %>
		<h4><b><%= @current_group.name %></b> - strona główna</h4>
	</div>
	<div id="main" class="panel-body" style="overflow-y: auto">
		<div class="row">
			<div class="col-md-3"></div>
			<div class="col-md-6">
				<% unless @news_to_show.nil? %>
					<% @news_to_show.each do |news| %>
						<div class="panel panel-default">
							<div class="panel-heading">
								<h4><%= news.title %></h4>
							</div>
							<div class="panel-body">
								<p lang="pl" style="hyphens: auto; text-align: justify">
									<% unless news.introduction.nil? %>
										<%= news.introduction %>
									<% else %>
										<%= news.content.gsub("<br />", " ")
												.truncate_words(60).html_safe %>
									<% end %>
								</p>
							</div>
							<div class="panel-footer">
								<% if @access_admin %>
									<div class="pull-right">
										<%= button_to "Usuń", acolyte_delete_news_url(id: news.id),
											  data: { confirm: "Czy na pewno chcesz usunąć " +
											  		"wiadomość <strong>" + news.title + "</strong>" },
											  method: :delete, class: "btn btn-danger btn-xs" %>
									</div>
								<% end %>
								<%= link_to "Czytaj", acolyte_show_news_url(id: news.id,
												page: @page),
								  	method: :get, class: "btn btn-default" %>
							</div>
						</div>
					<% end %>
				<% end %>
			</div>
			<div class="col-md-3"></div>
		</div>
	</div>
	<div id="main" class="panel-footer text-center">
		<nav aria-label="Page navigation">
		  <ul class="pagination">
		  	<li>
			  	<%= link_to "<span aria-hidden='true'>&laquo;</span>".html_safe,
			    		acolyte_index_url(page: 1), method: :get,
			    		"aria-label": "Pierwsza" %>
			  </li>
		    <li>
		      <%= link_to "<span aria-hidden='true'>&lsaquo;</span>".html_safe,
		    			acolyte_index_url(page: @page - 1), method: :get,
		    			"aria-label": "Poprzednia" %>
		    </li>
		    <% @pages_to_show.each do |i| %>
		    	<% if i == @page %>
		    		<li class="active">
		    			<span><%= i %><span class="sr-only">(current)</span></span>
		    		</li>
		    	<% else %>
		    		<li><%= link_to i, acolyte_index_url(page: i), method: :get %></li>
		    	<% end %>
		    <% end %>
		    <li>
		      <%= link_to "<span aria-hidden='true'>&rsaquo;</span>".html_safe,
		    			acolyte_index_url(page: @page + 1), method: :get,
		    			"aria-label": "Następna" %>
		    </li>
		    <li>
		    	<%= link_to "<span aria-hidden='true'>&raquo;</span>".html_safe,
		    			acolyte_index_url(page: @pages), method: :get,
		    			"aria-label": "Ostatnia" %>
		    </li>
		  </ul>
		</nav>
	</div>
</div>

app/views/acolyte/select_date_ranking.html.erb
<div id="main" class="panel panel-default">
	<div id="main" class="panel-heading">
		<h3>Ranking</h3>
	</div>
	<%= form_tag acolyte_show_ranking_url, method: :get do %>
		<div id="main" class="panel-body" style="overflow-y: auto">
			<h4>Wybierz zakres rankingu:</h4>
			<div class="form-group">
				<%= label_tag :start, "Od dnia" %>
				<div class="form-inline">
					<%= date_select :start, :date,
							{
								prompt: true,
								end_year: 2016,
								start_year: Date.today.year
							},
							{ class: "form-control" } %>
				</div>
			</div>
			<div class="form-group">
				<%= label_tag :end, "Do dnia" %>
				<div class="form-inline">
					<%= date_select :end, :date,
							{
								prompt: true,
								end_year: 2016,
								start_year: Date.today.year
							},
							{ class: "form-control" } %>
				</div>
			</div>
		</div>
		<div id="main" class="panel-footer">
			<div class="form-group" style="text-align: center">
				<%= button_tag "Pokaż", class: "btn btn-primary" %>
			</div>
		</div>
	<% end %>
</div>

app/views/acolyte/show_news.html.erb
<div id="main" class="panel panel-default">
	<div id="main" class="panel-heading">
		<h2><%= @news.title %></h2>
		<h5><b><%= l @news.created_at, format: :long %></b></h5>
		<% unless @news.author.nil? %>
			<h5>Napisał: <b><%= @news.author.full_name %></b></h5>
		<% end %>
	</div>
	<div id="main" class="panel-body" style="overflow-y: auto;">
		<p lang="pl" style="hyphens: auto; text-align: justify; line-height: 150%;
				font-size: 150%">
			<%= @news.content.html_safe %>
		</p>
	</div>
	<div id="main" class="panel-footer">
		<%= link_to "Wstecz", acolyte_index_url(page: params[:page]),
				method: :get, class: "btn btn-default" %>
		<% if @access_admin %>
			<div class="pull-right">
				<%= button_to "Usuń", acolyte_delete_news_url(id: @news.id),
					  data: { confirm: "Czy na pewno chcesz usunąć wiadomość" +
					  		" <strong>" + @news.title + "</strong>" },
					  method: :delete, class: "btn btn-danger btn-xs" %>
			</div>
		<% end %>
	</div>
</div>

app/views/acolyte/show_ranking.html.erb
<div id="main" class="panel panel-default">
	<div id="main" class="panel-heading">
		<h3>Ranking</h3>
	</div>
	<div id="main" class="panel-body" style="overflow-y: auto">
		<h4>Od <b><%= l @start, format: :long %></b>
		do <b><%= l @end, format: :long %></b></h4><br />
		<% @array = Array.new %>
		<% @current_group.users.sort_by{|u|
						@array[u.id] = u.points
								.where(event_id: @events.map(&:id))
								.sum(:points)
						-@array[u.id]
				}.each do |user| %>
			<% @points = @array[user.id] %>
			<%= (user.full_name + " (<b>" + @points.to_s + "</b>)").html_safe %>
			<br />
		<% end %>
	</div>
	<div id="main" class="panel-footer">
		<%= link_to "Wstecz", acolyte_select_date_ranking_url,
				method: :get, class: "btn btn-default" %>
	</div>
</div>

app/views/acolyte/show_schedule.html.erb
<div id="main" class="panel panel-default">
	<div id="main" class="panel-heading">
		<h4>Grafik</h4>
	</div>
	<div id="main" class="panel-body" style="overflow-y: auto">
		<% @categories.each do |category| %>
			<% if category.schedule_type == "weekly" %>
				<% @days = Array.new %>
				<% @hours_in_days = Array.new %>
				<% @hours = Array.new %>
				<div class="table-responsive">
					<table class="table table-bordered">
						<% unless category.nil? %>
							<% @title_show = false %>
							<% category.events.each do |event| %>
								<% @event_ok = false %>
								<% @properties =
										event.event_properties.where("mandatory_presence > ?", 0) %>
								<% if @properties.length > 0 and not @title_show %>
									<caption><%= category.name %></caption>
									<% @title_show = true %>
								<% end %>
								<% @properties.each do |property| %>
									<% if @event_ok =
											property.main_group.id == @current_group.id %>
										<% break %>
									<% end %>
								<% end %>
								<% if @event_ok %>
									<% if !@days.include? event.start_time.wday %>
										<% @days << event.start_time.wday %>
										<% @hours_in_days[event.start_time.wday] = Array.new %>
										<%= hidden_field_tag category.id.to_s +
											"[weekday][]", event.start_time.wday %>
									<% end %>
									<% if !@hours.include? event.start_time.to_s(:time) %>
										<% @hours << event.start_time.to_s(:time) %>
										<%= hidden_field_tag category.id.to_s +
											"[hour][]", event.start_time.to_s(:time) %>
									<% end %>
								<% end %>
							<% end %>
						<% end %>
						<thead>
							<tr>
								<th><div class="text-center">#</div></th>
								<% @days.sort!.each do |weekday| %>
									<% if weekday != 0 %>
										<th>
											<div class="text-center">
												<%= I18n.t(:"date.abbr_day_names")[weekday] %>
											</div>
										</th>
									<% end %>
								<% end %>
								<% @sunday = false %>
								<% @days.each do |weekday| %>
									<% if weekday == 0 %>
										<th>
											<div class="text-center">
												<%= I18n.t(:"date.abbr_day_names")[weekday] %>
											</div>
										</th>
										<% @sunday = true %>
										<% @days.delete(weekday) %>
									<% end %>
								<% end %>
								<% if @sunday == true %>
									<% @days << 0 %>
								<% end %>
							</tr>
						</thead>
						<tbody>
							<% @hours.sort!.each do |hour| %>
								<tr>
									<th scope="row">
										<div class="text-center"><%= hour %></div>
									</th>
									<% @days.each do |weekday| %>
										<td>
											<% category.events.each do |event| %>
												<% @event_ok = false %>
												<% event.event_properties
														.where("mandatory_presence > ?", 0)
														.each do |property| %>
													<% if @event_ok =
															property.main_group.id == @current_group.id %>
														<% break %>
													<% end %>
												<% end %>
												<% if @event_ok %>
													<% if event.start_time.wday == weekday and
															event.start_time.to_s(:time) == hour %>
														<% if !@hours_in_days.at(weekday)
																.include?(hour) %>
															<% @hours_in_days.at(weekday) << hour %>
															<div class="text-left text-capitalize">
																<% @current_group.users.each do |user| %>
																	<% @work_plan = user.work_plans.find_by(
																		main_group_id: @current_group.id) %>
																	<% unless @work_plan.nil? %>
																		<% @work_plan.tasks.where(event_id:
																				Event.where(event_category_id:
																					category.id)).each do |task| %>
																			<% if task.event.start_time.to_s(:time) ==
																					hour and task.event.start_time.wday ==
																					weekday %>
																				<%= user.first_name.first + ". " +
																					user.last_name %><br />
																				<% break %>
																			<% end %>
																		<% end %>
																	<% end %>
																<% end %>
															</div>
														<% end %>
													<% end %>
												<% end %>
											<% end %>
										</td>
									<% end %>
								</tr>
							<% end %>
						</tbody>
					</table>
				</div>
			<% end %>
		<% end %>
		</div>
		<% if !current_user.subgroups.where(admin: true,
				main_group_id: @current_group.id).empty? %>
			<div id="main" class="panel-footer">
				<div class="text-center">
					<%= button_to acolyte_generate_schedule_url,
							class: "btn btn-danger btn-xs pull-right" do %>
						Wyczyść obecny<br />i wygeneruj nowy grafik
					<% end %>
					<%= link_to "Edytuj", acolyte_edit_schedule_url,
						class: "btn btn-primary" %>
				</div>
			</div>
		<% end %>
	</div>
</div>

app/views/acolyte/write_news.html.erb
<div id="main" class="panel panel-default">
	<div id="main" class="panel-heading">
		<h3>Nowa wiadomość</h3>
	</div>
	<%= form_for News.new, url: acolyte_create_news_url,
			html: { method: :post } do |f| %>
		<div id="main" class="panel-body" style="overflow-y: auto; min-height: 220px">
			<div class="form-group">
				<%= f.label :title, "Tytuł" %>
				<%= f.text_field :title, autofocus: true, class: "form-control" %>
			</div>
			<div class="form-group">
				<%= f.label :content, "Tekst" %>
				<%= f.text_area :content, rows: 7, class: "form-control" %>
			</div>
		</div>
		<div id="main" class="panel-footer">
			<div class="pull-left">
				<%= link_to "Anuluj", acolyte_index_url,
					method: :get, class: "btn btn-default" %>
			</div>
			<div class="text-center">
				<%= f.submit "Dodaj" , class: "btn btn-primary" %>
			</div>
		</div>
	<% end %>
</div>