config/routes.rb
Rails.application.routes.draw do
	devise_for :users, controllers: {registrations: 'edit_profile',
		confirmations: 'confirmation'}
	
	get 'main_groups/manage'
	patch 'main_groups/edit'
	
	get 'subgroups/manage'
	patch 'subgroups/edit'
	
	get 'subgroups/show_users'
	patch 'subgroups/edit_users'
	
	get 'acolyte/index'
	get 'acolyte/user_offer_self_work'
	patch 'acolyte/save_dispositions'
	get 'acolyte/show_schedule'
	post 'acolyte/generate_schedule'
	get 'acolyte/edit_schedule'
	post 'acolyte/save_schedule'
	get 'acolyte/select_date_ranking'
	get 'acolyte/show_ranking'
	get 'acolyte/write_news'
	post 'acolyte/create_news'
	get 'acolyte/show_news'
	delete 'acolyte/delete_news'
	
	get 'calendar/show'
	get 'calendar/show_event'
	get 'calendar/add_event'
	post 'calendar/create_event'
	get 'calendar/show_event_to_edit'
	patch 'calendar/edit_event'
	delete 'calendar/destroy_event'
	delete 'calendar/destroy_event_series'
	get 'calendar/event_categories'
	patch 'calendar/event_category_edit'
	get 'calendar/show_attendance_list'
	get 'calendar/edit_attendance_list'
	get 'calendar/edit_mandatory_attendance_list'
	post 'calendar/save_attendance_list'
	post 'calendar/save_mandatory_attendance_list'
	get 'calendar/edit_points'
	post 'calendar/save_points'
	
	root 'home#index'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  PARAM_KEY_BLACKLIST = :authenticity_token, :commit, :utf8, :_method, :script_name
  
  def index
    @params = @view_context.respond_to?(:params) ? @view_context.params : Hash.new
    @params = @params.to_unsafe_h if @params.respond_to?(:to_unsafe_h)
    @params = @params.with_indifferent_access.except(*PARAM_KEY_BLACKLIST)
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-default">
	<div class="container">
		<!-- Brand and toggle get grouped for better mobile display -->
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed"
			data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"
			aria-expanded="false">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<%= link_to "Parafia Online", root_path, class: "navbar-brand" %>
		</div>

		<!-- Collect the nav links, forms, and other content for toggling -->
		<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
			<ul class="nav navbar-nav">
				<li><%= link_to "Ministranci", acolyte_index_url %></li>
			</ul>
			<ul class="nav navbar-nav navbar-right">
				<li><%= link_to "Ranking ministrantów",
						acolyte_select_date_ranking_url %></li>
				<% if user_signed_in? and
						(!current_user.subgroups.find_by(main_group_id:
						MainGroup.find_by(name: "Ministranci")).nil? or
						!current_user.subgroups.find_by(main_group_id:
						MainGroup.find_by(name: "Deweloperzy")).nil?) %>
					<li><%= link_to "Grafik", acolyte_show_schedule_url %></li>
				<% end %>
				<li><%= link_to "Kalendarium", calendar_show_url %></li>
				<% if user_signed_in? %>
					<li class="dropdown">
						<% if !current_user.subgroups.find_by(admin: true).nil? %>
							<a class="dropdown-toggle" data-toggle="dropdown" role="button"
							aria-haspopup="true" aria-expanded="false">
								Zarządzanie
								<span class="caret"></span>
							</a>
							<ul class="dropdown-menu">
								<% if !current_user.subgroups.find_by(admin: true).nil? %>
									<li><%= link_to "Kategorie wydarzeń",
										calendar_event_categories_url %></li>
									<li role="separator" class="divider"></li>
								<% end %>
								<% if !current_user.subgroups.find_by(main_group_id:
										MainGroup.find_by(name: "Deweloperzy")).nil? %>
									<li><%= link_to "Rangi",
										subgroups_manage_url %></li>
									<li><%= link_to "Grupy",
										main_groups_manage_url %></li>
									<li role="separator" class="divider"></li>
									<li><%= link_to "Deweloperzy",
										subgroups_show_users_url(group_name: "Deweloperzy") %></li>
								<% end %>
								<% if (!current_user.subgroups.find_by(main_group_id:
										MainGroup.find_by(name: "Użytkownicy")).nil? and
										current_user.subgroups.find_by(main_group_id:
										MainGroup.find_by(name: "Użytkownicy")).admin == true) or
										!current_user.subgroups.find_by(main_group_id:
										MainGroup.find_by(name: "Deweloperzy")).nil? %>
									<li><%= link_to "Użytkownicy",
										subgroups_show_users_url(group_name: "Użytkownicy") %></li>
								<% end %>
								<% if (!current_user.subgroups.find_by(main_group_id:
										MainGroup.find_by(name: "Ministranci")).nil? and
										current_user.subgroups.find_by(main_group_id:
										MainGroup.find_by(name: "Ministranci")).admin == true) or
										!current_user.subgroups.find_by(main_group_id:
										MainGroup.find_by(name: "Deweloperzy")).nil? %>
									<li><%= link_to "Ministranci",
										subgroups_show_users_url(group_name: "Ministranci") %></li>
								<% end %>
								<li class="dropdown-submenu">
									<a href="#">Hover me for more options</a>
									<ul class="dropdown-menu">
										<li><a href="#">Second level</a></li>
										<li class="dropdown-submenu pull-left">
											<a href="#">Even More... more... more...</a>
											<ul class="dropdown-menu">
												<li><a href="#">3rd level</a></li>
												<li><a href="#">3rd level</a></li>
											</ul>
										</li>
										<li><a href="#" id="test">Second level halo halo aloos sadas da</a></li>
										<li><a href="#">Second level</a></li>
									</ul>
								</li>
							</ul>
						<% end %>
					</li>
					<li class="dropdown">
						<a class="dropdown-toggle" data-toggle="dropdown" role="button"
						aria-haspopup="true" aria-expanded="false">
							<% if !current_user.first_name.nil? &&
									current_user.first_name != "" %>
								<%= current_user.first_name %>
							<% else %>
								Gall
							<% end %>
							<% if !current_user.last_name.nil? &&
									current_user.last_name != "" %>
								<%= current_user.last_name %>
							<% else %>
								Anonim
							<% end %>
							<span class="caret"></span>
						</a>
						<ul class="dropdown-menu">
							<% if !current_user.subgroups.find_by(main_group_id:
									MainGroup.find_by(name: "Ministranci")).nil? or
									!current_user.subgroups.find_by(main_group_id:
									MainGroup.find_by(name: "Deweloperzy")).nil? %>
								<li><%= link_to "Zadeklaruj gotowość to posług",
									acolyte_user_offer_self_work_url %></li>
								<li role="separator" class="divider"></li>
							<% end %>
							<li><%= link_to "Ustawienia konta",
								edit_user_registration_path %></li>
							<li><%= link_to "Wyloguj się",
								destroy_user_session_path,
								method: :delete %></li>
						</ul>
					</li>
				<% else %>
					<li><%= link_to "Zaloguj się",
						new_user_session_path %></li>
					<li><%= link_to "Zarejestruj się",
						new_user_registration_path %></li>
				<% end %>
			</ul>
		</div><!-- /.navbar-collapse -->
	</div><!-- /.container -->
</nav>

app/views/home/index.html.erb
<div class="jumbotron">
    <h1>Parafia Online</h1>
    <p>Strona główna</p>
</div>