config/routes.rb
Rails.application.routes.draw do
	devise_for :users, controllers: {registrations: 'edit_profile',
		confirmations: 'confirmation'}
	
	get 'main_groups/manage'
	patch 'main_groups/edit'
	
	get 'subgroups/manage'
	patch 'subgroups/edit'
	
	get 'subgroups/show_users'
	patch 'subgroups/edit_users'
	
	get 'acolyte/index'
	get 'acolyte/user_offer_self_work'
	patch 'acolyte/save_dispositions'
	get 'acolyte/show_schedule'
	post 'acolyte/generate_schedule'
	get 'acolyte/edit_schedule'
	post 'acolyte/save_schedule'
	get 'acolyte/select_date_ranking'
	get 'acolyte/show_ranking'
	get 'acolyte/write_news'
	post 'acolyte/create_news'
	get 'acolyte/show_news'
	delete 'acolyte/delete_news'
	
	get 'calendar/show'
	get 'calendar/show_event'
	get 'calendar/add_event'
	post 'calendar/create_event'
	get 'calendar/show_event_to_edit'
	patch 'calendar/edit_event'
	delete 'calendar/destroy_event'
	delete 'calendar/destroy_event_series'
	get 'calendar/event_categories'
	patch 'calendar/event_category_edit'
	get 'calendar/show_attendance_list'
	get 'calendar/edit_attendance_list'
	get 'calendar/edit_mandatory_attendance_list'
	post 'calendar/save_attendance_list'
	post 'calendar/save_mandatory_attendance_list'
	get 'calendar/edit_points'
	post 'calendar/save_points'
	
	root 'home#index'

end

app/models/subgroup.rb
class Subgroup < ActiveRecord::Base
    belongs_to :main_group
    has_and_belongs_to_many :users
end

app/controllers/subgroups_controller.rb
class SubgroupsController < ApplicationController
	before_action :authenticate_user!
	
	def manage
		if current_user.subgroups.find_by(
				main_group_id: MainGroup.find_by(name: "Deweloperzy")).nil?
			flash[:alert] = "Nie masz uprawnień do przeglądania tej podstrony."
			return redirect_to root_url
		end
	end
	
	def edit
		if current_user.subgroups.find_by(
				main_group_id: MainGroup.find_by(name: "Deweloperzy")).nil?
			flash[:alert] = "Nie masz uprawnień do przeglądania tej podstrony."
			return redirect_to root_url
		end
		if params[:delete]
			destroy
		elsif params[:subgroup][:name] != ""
			if params[:edit]
				if params[:selected_subgroup].nil?
					create
				else
					@founded_subgroup = Subgroup.find_by(
						name: params[:selected_subgroup_name])
					if (@founded_subgroup.name != params[:subgroup][:name] or
							@founded_subgroup.admin !=
								params[params[:selected_subgroup_name]][:admin] or
							@founded_subgroup.moderator !=
								params[params[:selected_subgroup_name]][:moderator]) and
							@founded_subgroup.update_attributes(subgroup_param)
						flash[:notice] = "Parametry rangi zostały zmienione."
						return redirect_to subgroups_manage_url
					else
						respond_to do |format|
							flash[:alert] = "Edycja się nie powiodła."
							return format.html { render :manage }
						end
					end
				end
			elsif params[:add]
				create
			end
		else
			respond_to do |format|
				flash[:alert] = "Nazwa rangi nie może być pusta."
				return format.html { render :manage }
			end
		end
	end
	
	def create
		if current_user.subgroups.find_by(
				main_group_id: MainGroup.find_by(name: "Deweloperzy")).nil?
			flash[:alert] = "Nie masz uprawnień do przeglądania tej podstrony."
			return redirect_to root_url
		end
		if params[:subgroup][:name] != ""
			@founded_main_group = MainGroup.find(params[:selected_main_group])
			@group = @founded_main_group.subgroups.build(subgroup_param)
			begin
				@group.save!
				flash[:notice] = "Stworzono nową grupę."
				return redirect_to subgroups_manage_url
			rescue ActiveRecord::RecordNotUnique
				respond_to do |format|
					flash[:alert] = "Ranga o tej nazwie już istnieje."
					return format.html { render :manage }
				end
			end
		else
			respond_to do |format|
				flash[:alert] = "Nazwa rangi nie może być pusta."
				return format.html { render :manage }
			end
		end
	end
	
	def destroy
		if current_user.subgroups.find_by(
				main_group_id: MainGroup.find_by(name: "Deweloperzy")).nil?
			flash[:alert] = "Nie masz uprawnień do przeglądania tej podstrony."
			return redirect_to root_url
		end
		@founded_subgroup = Subgroup.find_by(name: params[:selected_subgroup_name])
		@founded_subgroup.destroy
		flash[:notice] = "Usunięto rangę."
		return redirect_to subgroups_manage_url
	end
	
	def show_users
		@current_group = MainGroup.find_by(name: params[:group_name])
		@user_subgroup = current_user.subgroups.find_by(
			main_group_id: @current_group.id)
		if @current_group.nil?
			flash[:alert] = "Błąd dostępu poprzez nazwę grupy."
			return redirect_to root_url
		elsif (@user_subgroup.nil? or @user_subgroup.admin == false) and
				current_user.subgroups.find_by(main_group_id:
					MainGroup.find_by(name: "Deweloperzy").id).nil?
			flash[:alert] = "Nie masz uprawnień do przeglądania tej podstrony."
			return redirect_to root_url
		end
	end
	
	def edit_users
		@current_group = MainGroup.find_by(name: params[:group_name])
		@user_subgroup = current_user.subgroups.find_by(
			main_group_id: @current_group.id)
		if @current_group.nil?
			flash[:alert] = "Błąd dostępu poprzez nazwę grupy."
			return redirect_to root_url
		elsif (@user_subgroup.nil? or @user_subgroup.admin == false) and
				current_user.subgroups.find_by(main_group_id:
					MainGroup.find_by(name: "Deweloperzy").id).nil?
			flash[:alert] = "Nie masz uprawnień do przeglądania tej podstrony."
			return redirect_to root_url
		end
		User.all.each do |user|
			@subgroups = user.subgroups.find_by(main_group_id: @current_group.id)
			if params[user.email][:member] == "1"
				if @subgroups.nil?
					user.subgroups << Subgroup.find(params[user.email][:subgroup])
				else
					user.subgroups.delete(@subgroups)
					user.subgroups << Subgroup.find(params[user.email][:subgroup])
				end
			else if !@subgroups.nil?
					user.subgroups.delete(@subgroups)
				end
			end
		end
		flash[:notice] = "Lista członków grupy i ich rang została zapisana."
		return redirect_to subgroups_show_users_url(group_name: @current_group.name)
	end
	
	private
	def subgroup_param
		@sel_sub_name = params[:selected_subgroup_name]
		if @sel_sub_name != ""
			params[:subgroup][:admin] = params[@sel_sub_name][:admin]
			params[:subgroup][:moderator] = params[@sel_sub_name][:moderator]
		end
		params.require(:subgroup).permit(:name, :admin, :moderator)
	end
end

app/views/subgroups/manage.html.erb
<div id="main" class="panel panel-default">
	<div id="main" class="panel-heading">
		<h1>Zarządzanie rangami</h1>
	</div>
	<div id="main" class="panel-body" style="overflow-y: auto">
		<%= form_for Subgroup.new, url: subgroups_edit_url,
				html: { method: :patch } do |f| %>
			<div class="form-group">
				<div class="row">
					<div class="col-xs-6">
						<%= select_tag :selected_main_group,
						options_from_collection_for_select(
							MainGroup.all.collect.sort_by { |g| g.name },
							"id", "name"),
						{ class: "form-control", size: 10 } %>
					</div>
					<div class="col-xs-6">
						<%= select_tag :selected_subgroup,
						options_from_collection_for_select(
							Subgroup.all.collect.sort_by { |g| g.name },
							"main_group_id", "name"),
						{ class: "form-control", size: 10 } %>
						<%= hidden_field_tag :selected_subgroup_name, "" %>
					</div>
				</div>
			</div>
			<div class="text-right">
				<%= f.submit "Usuń", class: "btn btn-danger btn-xs",
				name: "delete", disabled: true,
				data: { confirm: "Czy na pewno chcesz usunąć rangę" } %>
			</div>
			<div class="text-center">
				<label class="checkbox-inline" id="subgroup_admin">
					<%= f.check_box :admin %>
					Administrator
				</label>
				<label class="checkbox-inline" id="subgroup_moderator">
					<%= f.check_box :moderator %>
					Moderator
				</label>
			</div>
			<% Subgroup.all.each do |g| %>
				<div class="text-center">
					<label class="checkbox-inline" style="display: none"
							id="<%= g.name + "_admin" %>">
						<%= check_box g.name, :admin, checked: g.admin %>
						Administrator
					</label>
					<label class="checkbox-inline" style="display: none"
							id="<%= g.name + "_moderator" %>">
						<%= check_box g.name, :moderator, checked: g.moderator %>
						Moderator
					</label>
				</div>
			<% end %>
			<div class="form-group">
				<%= f.label :name, "Nazwa grupy" %>
				<%= f.text_field :name, autocomplete: "off",
				class: "form-control" %>
			</div>
			<div class="text-center">
				<%= f.submit "Edytuj", class: "btn btn-primary",
				name: "edit", disabled: true %>
				<%= f.submit "Dodaj", class: "btn btn-primary",
				name: "add", disabled: true %>
			</div>
		<% end %>
	</div>
</div>
	

app/views/subgroups/show_users.html.erb
<div id="main" class="panel panel-default">
	<div id="main" class="panel-heading">
		<h1><%= @current_group.name %></h1>
	</div>
	<div id="main" class="panel-body" style="overflow-y: auto">
		<%= form_tag subgroups_edit_users_url,
				{ method: :patch, class: "form-horizontal" } do %>
			<%= hidden_field_tag :group_name, @current_group.name %>
			<% User.all.each do |user| %>
				<% @user_subgroup =
					user.subgroups.find_by(main_group_id: @current_group.id) %>
				<div class="form-group">
					<label class="col-sm-5 control-label">
						<%= user.first_name + " " + user.last_name +
							" (" + user.email + ")" %>
					</label>
					<div class="col-sm-2">
						<div class="text-center">
							<div class="checkbox">
								<%= check_box user.email, :member,
									checked: !@user_subgroup.nil? %>
								<%= "Ranga: " %>
							</div>
						</div>
					</div>
					<div class="col-sm-5">
						<%= select_tag user.email + "[subgroup]",
						options_from_collection_for_select(
							@current_group.subgroups.collect.sort_by {
								|g| g.name },
							"id", "name", if !@user_subgroup.nil?
								@user_subgroup.id else nil end),
						{ class: "form-control",
							disabled: @user_subgroup.nil?,
							include_blank: @user_subgroup.nil? } %>
					</div>
				</div>
			<% end %>
			<div class="text-center">
				<div class="form-group">
					<%= submit_tag "Zapisz", class: "btn btn-primary" %>
				</div>
			</div>
		<% end %>
	</div>
</div>